export enum CommonActionTypes {
    FETCH_CLIENT_CONFIG = "COMMON.FETCH_CLIENT_CONFIG",
    FETCH_CLIENT_CONFIG_SUCCESS = "COMMON.FETCH_CLIENT_CONFIG_SUCCESS",
    SHOW_LOADING_SPINNER = "COMMON.SHOW_LOADING_SPINNER",
    HIDE_LOADING_SPINNER = "COMMON.HIDE_LOADING_SPINNER"
}
